/**
 * Canonical core types. These are the integration seams that keep providers,
 * tools, the agent loop, and the UI decoupled. Everything that crosses a
 * package boundary speaks these types and nothing else.
 *
 * The shapes are adapted from charmbracelet/crush (the live successor to
 * opencode-ai/opencode): polymorphic message parts, a unified StreamPart
 * vocabulary (with first-class reasoning), and a Model struct that carries
 * reasoning + vision capability flags.
 */

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

/** A single piece of message content. Polymorphic by `type`. */
export type ContentPart =
  | TextPart
  | ReasoningPart
  | ImagePart
  | ToolCallPart
  | ToolResultPart
  | SuggestedActionsPart;

export interface TextPart {
  type: "text";
  text: string;
}

/** Reasoning/thinking tokens (GLM-5.2 reasoning models, Claude "thinking", etc.). */
export interface ReasoningPart {
  type: "reasoning";
  text: string;
  /** true while the model is still streaming this reasoning block. */
  partial?: boolean;
}

/** An image attached to a message (vision models only). */
export interface ImagePart {
  type: "image";
  /** data: URL or a remote URL the provider can fetch. */
  url: string;
  mimeType?: string;
}

/** The model requesting a tool execution. Lives on an assistant message. */
export interface ToolCallPart {
  type: "tool_call";
  id: string;
  name: string;
  /** Raw JSON string of arguments (parsed lazily by the dispatcher). */
  input: string;
}

/** The result of a tool execution. Lives on a `tool`-role message. */
export interface ToolResultPart {
  type: "tool_result";
  /** Matches the ToolCallPart.id it answers. */
  toolCallId: string;
  /** Matched tool name, for display. */
  name: string;
  content: string;
  /** Structured sidecar (counts, refs, timing). Optional. */
  metadata?: unknown;
  /** true => fed back to the model as an error, not thrown. */
  isError?: boolean;
}

/**
 * A single suggested follow-up the user can click to send. `label` is the short
 * chip text; `prompt` is the full user message that gets sent on click.
 */
export interface SuggestedAction {
  label: string;
  prompt: string;
}

/**
 * Suggested next actions shown under an assistant message. Either model-generated
 * (via the `suggest_actions` control tool) or a static fallback generated by the
 * loop. Persisted on the assistant message so it survives SW restarts.
 *
 * Intentionally excluded from the provider wire payload: `openai-compat.ts`
 * `partsText()` only reads text/reasoning parts, so this part never reaches the
 * model on subsequent turns.
 */
export interface SuggestedActionsPart {
  type: "suggested_actions";
  actions: SuggestedAction[];
}

export type MessageRole = "system" | "user" | "assistant" | "tool";

/** A message is a role + an ordered list of parts. */
export interface Message {
  id: string;
  role: MessageRole;
  parts: ContentPart[];
  createdAt: number;
}

// ---------------------------------------------------------------------------
// Streaming — the unified vocabulary every provider emits.
// ---------------------------------------------------------------------------

export type StreamPartType =
  // text
  | "text_start"
  | "text_delta"
  | "text_end"
  // reasoning / thinking
  | "reasoning_start"
  | "reasoning_delta"
  | "reasoning_end"
  // tool input (streamed argument JSON)
  | "tool_input_start"
  | "tool_input_delta"
  | "tool_input_end"
  | "tool_call"
  // terminal
  | "finish"
  | "error"
  | "warning";

export interface StreamPart {
  type: StreamPartType;

  // text / reasoning deltas
  delta?: string;

  // tool_input_*: the id + name being accumulated.
  toolCallId?: string;
  toolCallName?: string;

  // a complete, parsed tool call (emitted at the end of accumulation).
  toolCall?: ToolCallPart;

  // finish
  finishReason?: FinishReason;
  usage?: TokenUsage;

  // error / warning
  error?: { message: string; status?: number; retryable?: boolean };
  warning?: string;
}

export type FinishReason =
  | "end_turn"
  | "max_tokens"
  | "tool_use"
  | "canceled"
  | "error"
  | "permission_denied"
  | "unknown";

export interface TokenUsage {
  input: number;
  output: number;
  /** Cached prompt tokens (Anthropic prompt caching, OpenAI cached). */
  cachedInput?: number;
  /** Reasoning tokens (o1/GLM-5.x thinking). */
  reasoning?: number;
}

// ---------------------------------------------------------------------------
// Provider + model metadata
// ---------------------------------------------------------------------------

/**
 * Per-model capability + pricing metadata. The capability flags are richer
 * than opencode's (which assumed tools/streaming universal): local/compat
 * models frequently lack tool-calling or vision, so we gate behavior on these.
 */
export interface Model {
  /** Stable internal id. May differ from the wire name (see `apiName`). */
  id: string;
  /** Display name. */
  name: string;
  /** The wire name sent to the API. Often equals `id`. */
  apiName: string;
  /** Owning provider id. */
  provider: string;

  contextWindow: number;
  defaultMaxTokens: number;

  // pricing per 1M tokens (USD). 0 / undefined => unknown.
  costPer1MIn?: number;
  costPer1MOut?: number;
  costPer1MInCached?: number;

  // capabilities
  canReason?: boolean;
  reasoningLevels?: string[];
  defaultReasoningEffort?: string;
  /** vision / multimodal */
  supportsAttachments?: boolean;
  supportsTools?: boolean;
  supportsStreaming?: boolean;
  supportsJsonMode?: boolean;
  supportsParallelToolCalls?: boolean;
}

/**
 * Auth-field schema. Each provider declares the fields its connect UI must
 * render. The UI itself is fully generic and contains no provider-specific
 * logic, satisfying the "UI must NOT contain provider-specific logic" rule.
 */
export interface AuthField {
  key: string;
  label: string;
  type: "password" | "text" | "url";
  required: boolean;
  placeholder?: string;
  help?: string;
}

/**
 * A provider definition from the catalog. The adapter is chosen by `type`;
 * everything else is data. Adding a new OpenAI-compat provider = one entry.
 */
export interface ProviderDefinition {
  id: string;
  name: string;
  /** Short label shown in the provider chip. */
  shortName?: string;
  /** Single-glyph or short emoji shown in the brand chip. */
  icon?: string;
  /** Brand color (hex) for the chip background / accent. */
  brandColor?: string;
  /** Adapter family. Drives the registry factory. */
  type: "openai-compat" | "anthropic" | "gemini";
  baseURL: string;
  /** Where to GET /models for dynamic discovery + validation. */
  modelsEndpoint?: string;
  authFields: AuthField[];
  /** Extra HTTP headers to send on every request (e.g. OpenRouter's X-Title). */
  extraHeaders?: Record<string, string>;
  /**
   * Extra JSON merged into the chat request body. Used for provider quirks
   * like Z.AI's `tool_stream: true`. Evaluated per-request so it can depend
   * on the selected model.
   */
  extraBody?: ExtraBodyFn | Record<string, unknown>;
  /** Default model id when the user has not picked one. */
  defaultLargeModelId?: string;
  defaultSmallModelId?: string;
  /** Subscription providers (Z.AI coding plan) skip per-token cost display. */
  flatRate?: boolean;
  /** Seed model list (dynamic discovery merges on top). */
  models: Model[];
  docsUrl?: string;
}

/** Per-request extraBody, given the selected model + whether reasoning is on. */
export type ExtraBodyFn = (ctx: {
  model: Model;
  reasoning: boolean;
}) => Record<string, unknown>;

/**
 * Resolved provider config (after the user connects). The adapter reads from
 * this at request time. Credentials live ONLY in storage.session at runtime;
 * the encrypted at-rest copy is decrypted into here on session start.
 */
export interface ProviderConfig {
  definition: ProviderDefinition;
  /** keyed by AuthField.key */
  credentials: Record<string, string>;
  /** the user's chosen default model id within this provider. */
  selectedModelId: string;
}

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

/** JSON-schema for a tool parameter, in the OpenAI function-calling shape. */
export interface ToolParameterSchema {
  type: string;
  description?: string;
  enum?: string[];
  items?: ToolParameterSchema;
  properties?: Record<string, ToolParameterSchema>;
  required?: string[];
}

export interface ToolInfo {
  name: string;
  description: string;
  parameters: ToolParameterSchema;
}

export interface ToolCall {
  id: string;
  name: string;
  /** Parsed arguments object. */
  input: Record<string, unknown>;
}

export interface ToolResult {
  toolCallId: string;
  name: string;
  content: string;
  metadata?: unknown;
  isError?: boolean;
}

// ---------------------------------------------------------------------------
// Agent session (persisted, per tab)
// ---------------------------------------------------------------------------

export type SessionState =
  | "idle"
  | "attaching"
  | "running"
  | "streaming"
  | "tool"
  | "awaiting_permission"
  | "awaiting_plan_approval"
  | "pausing"
  | "paused"
  | "compacting"
  | "done"
  | "error"
  | "resuming";

/** What the loop is doing / about to do at a checkpoint. */
export type StepIntent =
  | { stepId: number; kind: "stream" }
  | { stepId: number; kind: "tool"; toolCalls: ToolCallPart[] };

/** A single todo in the agent's proposed plan (the checklist shown on approval). */
export interface PlanStep {
  id: string;
  title: string;
  detail?: string;
  status: "pending" | "progress" | "done";
}

/** A user message waiting to be delivered: steered mid-run or queued for after. */
export interface QueuedMessage {
  id: string;
  text: string;
  createdAt: number;
}

/** A proposed plan + whether the user approved it this run. */
export interface SessionPlan {
  planId: string;
  steps: PlanStep[];
  /** Epoch ms when the user approved; null while pending / if rejected. */
  approvedAt: number | null;
}

export interface Session {
  sessionId: string;
  tabId: number;
  providerId: string;
  modelId: string;
  state: SessionState;

  history: Message[];

  runId: string;
  /** Last origin approved for this run; persists across worker recovery. */
  approvedOrigin?: string;
  stepId: number;
  pendingStep: StepIntent | null;
  /** The assistant message currently being streamed (committed only on finish). */
  streamingAssistantId: string | null;

  usage: TokenUsage;
  costUsd: number;
  contextWindow: number;
  /** True when the provider is flatRate (subscription); cost display is hidden. */
  flatRate: boolean;
  /** History index where a compaction summary begins (0 = none). */
  compactedUpTo: number;

  createdAt: number;
  updatedAt: number;
  abortReason: string | null;

  debuggerAttached: boolean;

  /** Plan-approval workflow state (ask mode). */
  plan: SessionPlan | null;
  /** Run ID for which the current plan was approved. Equality with s.runId
   *  means "plan approved this run -> skip per-action prompts". */
  planApprovedRunId: string | null;

  /** User messages sent while a run was active. Drained at the top of each
   *  loop iteration (steering) and/or after the run finishes (queue). */
  messageQueue: QueuedMessage[];
}

export const NON_IDLE_STATES: SessionState[] = [
  "attaching",
  "running",
  "streaming",
  "tool",
  "awaiting_permission",
  "awaiting_plan_approval",
  "pausing",
  "compacting",
  "resuming",
];

// ---------------------------------------------------------------------------
// Misc
// ---------------------------------------------------------------------------

export class NotImplementedError extends Error {
  constructor(what: string) {
    super(`Not implemented: ${what}`);
    this.name = "NotImplementedError";
  }
}

/** Stable id generator. crypto.randomUUID in all modern browsers/SW. */
export function uuid(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return "xxxxxxxxxxxx4xxxyxxxxxxxxxxxxxxx".replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === "x" ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}
